# Generated by Django 5.2.5 on 2025-11-11 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingest", "0001_initial"),
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ui.folder",
            ),
        ),
        migrations.AddField(
            model_name="excerpt",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ingest.document",
            ),
        ),
    ]
