# Generated by Django 5.2.5 on 2025-11-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0002_initial"),
        ("ui", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="folder",
        ),
        migrations.AddField(
            model_name="document",
            name="folder",
            field=models.ManyToManyField(blank=True, null=True, to="ui.folder"),
        ),
    ]
