# Generated by Django 5.2.5 on 2025-11-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0003_remove_document_folder_document_folder"),
        ("ui", "0004_delete_file"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Document",
            new_name="File",
        ),
    ]
