# Generated by Django 5.2.5 on 2026-01-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0004_rename_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(default=None, upload_to="uploaded_documents/"),
        ),
    ]
