# Generated by Django 5.2.5 on 2026-01-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0006_alter_file_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(default=None, upload_to="media/"),
        ),
    ]
