# Generated by Django 5.2.5 on 2026-02-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0007_alter_file_file"),
        ("ui", "0004_delete_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="folder",
            field=models.ManyToManyField(
                blank=True, related_name="files", to="ui.folder"
            ),
        ),
    ]
