# Generated by Django 5.2.5 on 2025-11-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="user_files/"
            ),
        ),
    ]
