# Generated by Django 5.2.5 on 2025-11-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0003_alter_file_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="File",
        ),
    ]
